apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: rucio
  name: rucio
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: rucio
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: rucio
    spec:
      containers:
      - name: rucio
        image: aaarora/rucio-deploy:latest
        imagePullPolicy: Always
        env:
        - name: DB_ADDR
          value: 192.168.25.94 
        - name: OSG_FQDN
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 443
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 1
            memory: 2Gi
        volumeMounts:
        - name: rucio-conf
          mountPath: /opt/rucio/etc/rucio.cfg
          subPath: rucio.cfg
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: rucio-conf
        configMap:
          name: rucio-conf
          items:
          - key: rucio.cfg
            path: rucio.cfg
