resources:
  - deploy.yaml

configMapGenerator:
  - name: rucio-conf
    files:
      - rucio.cfg
      - alembic.ini
  - name: rucio-misc-scripts
    files:
      - add-rse.sh

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  k8s-app: rucio
