#!/bin/bash

cat <<EOF > deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: rucio
  name: rucio
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: rucio
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: rucio
    spec:
      containers:
      - name: rucio
        image: aaarora/rucio-deploy:latest
        imagePullPolicy: Always
        env:
        - name: DB_ADDR
          value: $(kubectl get pods -l k8s-app=postgres -o jsonpath="{.items[0].status.podIP}") 
        - name: OSG_FQDN
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8446
        - containerPort: 8449
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 1
            memory: 2Gi
        volumeMounts:
        - name: rucio-conf
          mountPath: /etc/rucio3/rucio3config
          subPath: rucio3config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: rucio-conf
        configMap:
          name: rucio-conf
          items:
          - key: rucio3config
            path: rucio3config
EOF
