resources:
  - deploy.yaml

configMapGenerator:
  - name: xrootd-server-conf
    files:
      - xrootd-third-party-copy.cfg
      - auth-file-noauth
  - name: xrootd-server-supervisor
    files:
      - supervisord.conf
  - name: cert-script
    files:
      - cagen.py

secretGenerator:
  - name: https-self-certs
    files:
      - OSG-Test-CA.pem

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app: xrootd-server
