apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: fts
  name: fts
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: fts
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: fts
    spec:
      containers:
      - name: fts
        image: aaarora/fts-deploy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 1
            memory: 2Gi
        volumeMounts:
        - name: fts-conf
          mountPath: /etc/fts3/fts3config
          subPath: fts3config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: fts-conf
        configMap:
          name: fts-conf
          items:
          - key: fts3config
            path: fts3config
